#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SOURCE_DIR="${1:-${REPO_ROOT}/.claude/rules}"
TARGET_DIR="${2:-${REPO_ROOT}/.github/instructions/claude-rules}"
MANIFEST_PATH="${TARGET_DIR}/.claude-rules-sync-manifest"

if [[ ! -d "${SOURCE_DIR}" ]]; then
  echo "Source directory does not exist: ${SOURCE_DIR}" >&2
  exit 1
fi

mkdir -p "${TARGET_DIR}"

tmp_manifest="$(mktemp)"
trap 'rm -f "${tmp_manifest}"' EXIT

generated_count=0

extract_apply_to() {
  local rule_path="$1"

  awk '
    BEGIN { in_frontmatter = 0; in_paths = 0 }

    NR == 1 && $0 == "---" {
      in_frontmatter = 1
      next
    }

    in_frontmatter && $0 == "---" {
      exit
    }

    in_frontmatter && $0 ~ /^[[:space:]]*paths:[[:space:]]*$/ {
      in_paths = 1
      next
    }

    in_frontmatter && in_paths && $0 ~ /^[[:space:]]*-[[:space:]]*".*"[[:space:]]*$/ {
      line = $0
      sub(/^[[:space:]]*-[[:space:]]*"/, "", line)
      sub(/"[[:space:]]*$/, "", line)
      print line
      next
    }

    in_frontmatter && in_paths && $0 ~ /^[[:space:]]*$/ {
      next
    }

    in_frontmatter && in_paths {
      in_paths = 0
    }
  ' "${rule_path}" | paste -sd ',' -
}

process_rule_file() {
  local rule_file="$1"
  rule_name="$(basename "${rule_file}" .md)"
  apply_to="$(extract_apply_to "${rule_file}")"

  if [[ -z "${apply_to}" ]]; then
    apply_to="**"
  fi

  target_file="${TARGET_DIR}/${rule_name}.instructions.md"

  cat > "${target_file}" <<EOF
---
applyTo: "${apply_to}"
---

<!-- Generated by scripts/sync_claude_rules_to_copilot.sh. -->
<!-- Canonical source: .claude/rules/${rule_name}.md -->

# Copilot Bridge: ${rule_name}

Read and apply
\`.claude/rules/${rule_name}.md\` before editing files matching this scope.

Do not duplicate or rewrite rule content here.
If this bridge and the canonical rule disagree, the canonical rule wins.
EOF

  printf '%s\n' "${rule_name}" >> "${tmp_manifest}"
  generated_count=$((generated_count + 1))
}

if command -v fd >/dev/null 2>&1; then
  while IFS= read -r -d '' rule_file; do
    process_rule_file "${rule_file}"
  done < <(fd --absolute-path --type f --extension md . "${SOURCE_DIR}" -0 | sort -z)
else
  while IFS= read -r -d '' rule_file; do
    process_rule_file "${rule_file}"
  done < <(find "${SOURCE_DIR}" -mindepth 1 -maxdepth 1 -type f -name '*.md' -print0 | sort -z)
fi

if [[ -f "${MANIFEST_PATH}" ]]; then
  while IFS= read -r previous_rule; do
    [[ -n "${previous_rule}" ]] || continue
    if ! grep -Fqx "${previous_rule}" "${tmp_manifest}"; then
      rm -f "${TARGET_DIR:?}/${previous_rule}.instructions.md"
    fi
  done < "${MANIFEST_PATH}"
fi

mv "${tmp_manifest}" "${MANIFEST_PATH}"
trap - EXIT

echo "Generated ${generated_count} Copilot bridge instruction file(s) in ${TARGET_DIR}"
